server:
  port: ${PORT:8080}

spring:
  application:
    name: bob-gateway-service
  active:
    profiles: ${APP_PROFILE:local}
  cloud:
    gateway:
      routes:
        - id: bob-auth-service
          uri: lb://BOB-AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: bob-member-service
          uri: lb://BOB-MEMBER-SERVICE
          predicates:
            - Path=/members/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${server.port}

management:
  endpoint:
    gateway:
      enabled: true # default value
  endpoints:
    web:
      exposure:
        include: "gateway"