server:
  port: ${PORT:8080}

spring:
  application:
    name: bob-gateway-service
  active:
    profiles: ${APP_PROFILE:local}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${server.port}